### ISSUE TITLE
Make it clearer this is CRA-compatible (for react-scripts@2.x)

### ISSUE THREAD

**Issue by gaearon** [evenchange4/graphql.macro#2]
From the README

>Note: You'll also need to install and configure babel-plugin-macros if you haven't already.

This makes it seem like if you use CRA you'd have to eject.

Could you clarify this works with CRA if you use `2.x` of `react-scripts`?

**Comment by evenchange4** [comment]
Updated via https://github.com/evenchange4/graphql.macro/commit/4a12d5ae8c4ba21e64af34e00e626b4893f63282 🙌
