### ISSUE TITLE
Module not found: Can't resolve 'module' in '/Users/Documents/git/project-name/node_modules/require-from-string'

### ISSUE THREAD

**Issue by jpdorsy** [evenchange4/graphql.macro#25]
Environment: create-react-app (forked https://www.npmjs.com/package/custom-react-scripts)

Code change:
// import gql from 'graphql-tag';
import { gql } from 'graphql.macro';

Problem: Switching to use graphql.macro from graphql-tag throws following error:

```
Failed to compile.

./node_modules/require-from-string/index.js
Module not found: Can't resolve 'module' in '/Users/Documents/git/fwota-ui/node_modules/require-from-string'
```

**Comment by evenchange4** [comment]
Hi @jpdorsy, thank you for for reporting it.
Unfortunately, I can not reproduce it. Would you like to provide more information?
Here is the [demo](https://github.com/evenchange4/graphql.macro-example/blob/gql-demo/src/App.js#L7-L21) of the `gql` use case.

**Comment by jpdorsy** [comment]
Thanks, your demo contains react-scripts@2.x. Does the graphql.macro work in react-scripts@1.x.x?

**Comment by evenchange4** [comment]
No, the graphql.macro does not work with 1.x. :(
The `Babel Macros` solution is only supported in [2.0](https://github.com/facebook/create-react-app/issues/3815).

**Comment by jpdorsy** [comment]
If graphql.macro only supports 2.x.x, as per this link (https://github.com/facebook/create-react-app/pull/3909) isn't the .graphql file support already added to 2.x.x? Do we still need graphql.macro in that case? thanks.
