### ISSUE TITLE
Same same but different?

### ISSUE THREAD

**Issue by zimme** [evenchange4/graphql.macro#3]
https://github.com/leoasis/graphql-tag.macro

**Comment by evenchange4** [comment]
@zimme Thanks for asking. 

I implement `graphql.macro` for the proposal of **webpack loader** ([the first use case](https://github.com/evenchange4/graphql.macro#loader)) feature in [CRA issue#1792](https://github.com/facebookincubator/create-react-app/issues/1792#issuecomment-358069544). 
Then I found there is already a graphql-related library `graphql-tag.macro` so I integrate the same functionality of **gql** ([the second use case](https://github.com/evenchange4/graphql.macro#gql)) feature.
Yes, you can use both at the same time. I already list it in the [alternative section](https://github.com/evenchange4/graphql.macro#alternative). 😀

**Comment by zimme** [comment]
Aaah, that's awesome!
