### ISSUE TITLE
Support absolute imports than only relative

### ISSUE THREAD

**Issue by vinhlh** [evenchange4/graphql.macro#36]
Looks like currently we only support relative paths https://github.com/evenchange4/graphql.macro/blob/master/src/macro.js#L31

**Comment by audiolion** [comment]
this is a killer for me, I have a mono-repo setup and it isn't finding my graphql imports

**Comment by smilexu** [comment]
same issue for me, especially you need to import fragment which located in different folder as query file, that would be the hell

**Comment by jdgreenberger** [comment]
Would it be possible to handle absolute imports using tsconfig as well?
