### ISSUE TITLE
Fix flow type for fragments

### ISSUE THREAD

**Issue by mufasa71** [evenchange4/graphql.macro#66]
Example:
```
// @flow
import { gql } from 'graphql.macro'
const PostFragment = gql`
  fragment Post on PostType {
    title,
    date
  }
`

const GET_POSTS = gql`
  query getPosts {
    ...PostFragment
  }

  ${PostFragment}
`
```
Produces:
`Cannot call gql because no more than 1 argument is expected by function`

**Comment by evenchange4** [comment]
Thanks for reporting the issue!
Close it. Please feel free to reopen this issue if the problem still occurs with a newer version `v1.3.4`.
