### ISSUE TITLE
Support create-react-app v3 absolute imports?

### ISSUE THREAD

**Issue by FezVrasta** [evenchange4/graphql.macro#92]
I have my fixtures into `src/fixtures`, it would be great to be able to `const query = loader('fixtures/query')` rather than having to specify the full relative path.

Is this something that this library could implement?

**Comment by FezVrasta** [comment]
It seems like support for `NODE_PATH` has been implemented with https://github.com/evenchange4/graphql.macro/issues/36, but CRA v3 changed the way we configure the parameter so it doesn't work anymore.

**Comment by evenchange4** [comment]
Thanks! Released `v1.4.0` with your changes. 🙌

**Comment by FezVrasta** [comment]
Great thanks!

**Comment by gastonmorixe** [comment]
@FezVrasta @evenchange4 It would be helpful if we could support `tsconfig.json` files too
